### ISSUE TITLE
Dsyms files not found when mounting sentry-data volume

### ISSUE THREAD

**Issue by HenryHaoson** [getsentry/onpremise#1137]
### Version

21.10.0

### Steps to Reproduce

volumes config:

```yml
volumes:
  sentry-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/sentry-data/_data
  sentry-postgres:
    external: true
  sentry-redis:
    external: true
  sentry-zookeeper:
    external: true
  sentry-kafka:
    external: true
  sentry-clickhouse:
    external: true
  sentry-symbolicator:
    external: true
  sentry-secrets:
  sentry-smtp:
  sentry-zookeeper-log:
  sentry-kafka-log:
  sentry-smtp-log:
  sentry-clickhouse-log:
```

### Expected Result

proguard files can be downloaded and work fine

### Actual Result

proguard files were listed, but cannot download them.
![image](https://user-images.githubusercontent.com/22147654/140469717-ba904759-8be7-43b2-a863-0e3c5161b0ca.png)
![image](https://user-images.githubusercontent.com/22147654/140469958-b7eba8ec-4335-43be-b539-0dedf52a8e5e.png)

![image](https://user-images.githubusercontent.com/22147654/140469882-b8fc7c5b-2c20-4887-82f6-4db48c3b618a.png)

proguad files not work fine
![image](https://user-images.githubusercontent.com/22147654/140470531-79e9260a-ff27-4bce-8ac0-b698aac67ba6.png)
