### ISSUE TITLE
Mail Event-Notifications not working

### ISSUE THREAD

**Issue by Chrissi2812** [getsentry/onpremise#287]
So my problem is that the alerts are not send out via mail.
Even after adding the **Send notification via Mail**
![image](https://user-images.githubusercontent.com/6141652/69863983-5ea18d80-129e-11ea-8e75-90504b044941.png)

User Feedback, Invites and Test Mails are working fine.

When looking in `docker logs sentry_worker_1 --follow` only mails for the user feedback get added.

I have used the default smtp server.

The only change I have made was adding my mail address to the config. And I had to add the hostname for the smtp container, because mail got rejected with no FQDN or IP set error.
After that I run `docker-compose build`.

```yaml
services:
  smtp:
    << : *restart_policy
    image: tianon/exim4
    hostname: ***hostname of my server**
```

Am I missing something? 

I am using `sentry, version 10.0.0.dev0`
