### ISSUE TITLE
upgrade 9.0 -> 9.1.2 -> 10

### ISSUE THREAD

**Issue by chi-miel** [getsentry/onpremise#387]
Good morning,

I updated sentry 9.0 to 9.1.2, I checkedout sentry 9.1.2 and kept my data with "external: true" for data and postgre volumes:

```
volumes:
  sentry-data:
    #external: true
  sentry-postgres:
    #external: true
```
then I ran the README upgrade:
```
docker-compose build --pull # Build the services again after updating, and make sure we're up to date on patch version
docker-compose run --rm web upgrade # Run new migrations
docker-composes up -d # Recreate the services

```
Everything's working, I've saved my data and sentry's configuration.

I wanted to upgrade from 9.1.2 to 10.

I checked out the branch master.
I commented "external: true" for the postgre and data volumes and renamed the volumes to match the existing volumes:
 ```
 onpremise_sentry-data:
    #external: true
  onpremise_sentry-postgres:
    #external: true
```

then I followed the procedure: https://github.com/getsentry/onpremise/issues/278#issuecomment-567809679
=> I lost my data and configuration

I ran the install.sh script
=> I lost my data and my configuration

this is my docker-composer in 9.1.2:

```
# NOTE: This docker-compose.yml is meant to be just an example of how
# you could accomplish this on your own. It is not intended to work in
# all use-cases and must be adapted to fit your needs. This is merely
# a guideline.

# See docs.getsentry.com/on-premise/server/ for full
# instructions

version: '3.4'

x-logging:
  &default-logging
  driver: syslog
  options:
    syslog-facility: local0
    syslog-address: tcp://127.0.0.1:514

x-defaults: &defaults
  restart: unless-stopped
  build:
    context: .
  depends_on:
    - redis
    - postgres
    - memcached
#    - smtp
  env_file: .env
  environment:
    # Run `docker-compose run web config generate-secret-key`
    # to get the SENTRY_SECRET_KEY value.
    SENTRY_SECRET_KEY: 3pi=kv=nabrfid6j+0#*n+vxgdpdkygtmx&w-mce9@sdy_i-&p
    SENTRY_MEMCACHED_HOST: memcached
    SENTRY_REDIS_HOST: redis
    SENTRY_POSTGRES_HOST: postgres
    SENTRY_EMAIL_HOST: 172.17.0.1
    SENTRY_SERVER_EMAIL: sentry@eolas.fr
  volumes:
    - sentry-data:/var/lib/sentry/files


services:
#  smtp:
#    restart: unless-stopped
#    image: tianon/exim4

  memcached:
    restart: unless-stopped
    image: memcached:1.5-alpine
    logging: *default-logging

  redis:
    restart: unless-stopped
    image: redis:3.2-alpine
    logging: *default-logging

  postgres:
    restart: unless-stopped
    image: postgres:9.5
    volumes:
      - sentry-postgres:/var/lib/postgresql/data
    logging: *default-logging

  web:
    <<: *defaults
    ports:
      - '9000:9000'
    logging:
      driver: none

  cron:
    <<: *defaults
    command: run cron
    logging: *default-logging

  worker:
    <<: *defaults
    command: run worker
    logging: *default-logging

volumes:
    sentry-data:
#      external: true
    sentry-postgres:
 #     external: true

```

this is my docker-composes in 10:

```
version: '3.4'
x-restart-policy: &restart_policy
  restart: unless-stopped
x-sentry-defaults: &sentry_defaults
  << : *restart_policy
  build:
    context: ./sentry
    args:
      - SENTRY_IMAGE
  image: sentry-onpremise-local
  depends_on:
    - redis
    - postgres
    - memcached
    - smtp
    - snuba-api
    - snuba-consumer
    - snuba-replacer
    - symbolicator
    - kafka
  environment:
    SNUBA: 'http://snuba-api:1218'
  volumes:
    - 'onpremise_sentry-data:/data'
x-snuba-defaults: &snuba_defaults
  << : *restart_policy
  depends_on:
    - redis
    - clickhouse
    - kafka
  image: 'getsentry/snuba:latest'
  environment:
    SNUBA_SETTINGS: docker
    CLICKHOUSE_HOST: clickhouse
    DEFAULT_BROKERS: 'kafka:9092'
    REDIS_HOST: redis
    # TODO: Remove these after getsentry/snuba#353
    UWSGI_MAX_REQUESTS: '10000'
    UWSGI_DISABLE_LOGGING: 'true'
    UWSGI_ENABLE_THREADS: 'true'
    UWSGI_DIE_ON_TERM: 'true'
    UWSGI_NEED_APP: 'true'
    UWSGI_IGNORE_SIGPIPE: 'true'
    UWSGI_IGNORE_WRITE_ERRORS: 'true'
    UWSGI_DISABLE_WRITE_EXCEPTION:  'true'
services:
  smtp:
    << : *restart_policy
    image: tianon/exim4
    volumes:
      - 'sentry-smtp:/var/spool/exim4'
      - 'sentry-smtp-log:/var/log/exim4'
  memcached:
    << : *restart_policy
    image: 'memcached:1.5-alpine'
  redis:
    << : *restart_policy
    image: 'redis:5.0-alpine'
    volumes:
      - 'sentry-redis:/data'
  postgres:
    << : *restart_policy
    image: 'postgres:9.6'
    volumes:
      - 'onpremise_sentry-postgres:/var/lib/postgresql/data'
  zookeeper:
    << : *restart_policy
    image: 'confluentinc/cp-zookeeper:5.1.2'
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'
      CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: 'WARN'
      ZOOKEEPER_TOOLS_LOG4J_LOGLEVEL: 'WARN'
    volumes:
      - 'sentry-zookeeper:/var/lib/zookeeper/data'
      - 'sentry-zookeeper-log:/var/lib/zookeeper/log'
      - 'sentry-secrets:/etc/zookeeper/secrets'
  kafka:
    << : *restart_policy
    depends_on:
      - zookeeper
    image: 'confluentinc/cp-kafka:5.1.2'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_LOG4J_LOGGERS: 'kafka.cluster=WARN,kafka.controller=WARN,kafka.coordinator=WARN,kafka.log=WARN,kafka.server=WARN,kafka.zookeeper=WARN,state.change.logger=WARN'
      KAFKA_LOG4J_ROOT_LOGLEVEL: 'WARN'
      KAFKA_TOOLS_LOG4J_LOGLEVEL: 'WARN'
    volumes:
      - 'sentry-kafka:/var/lib/kafka/data'
      - 'sentry-kafka-log:/var/lib/kafka/log'
      - 'sentry-secrets:/etc/kafka/secrets'
  clickhouse:
    << : *restart_policy
    image: 'yandex/clickhouse-server:19.11'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - 'sentry-clickhouse:/var/lib/clickhouse'
  snuba-api:
    << : *snuba_defaults
  snuba-consumer:
    << : *snuba_defaults
    command: consumer --auto-offset-reset=latest --max-batch-time-ms 750
  snuba-replacer:
    << : *snuba_defaults
    command: replacer --auto-offset-reset=latest --max-batch-size 3
  snuba-cleanup:
    << : *snuba_defaults
    image: snuba-cleanup-onpremise-local
    build:
      context: ./cron
      args:
        BASE_IMAGE: 'getsentry/snuba:latest'
        http_proxy: ****************
        https_proxy: ****************
        ftp_proxy: ****************
    command: '"*/5 * * * * gosu snuba snuba cleanup --dry-run False"'
  symbolicator:
    << : *restart_policy
    image: 'getsentry/symbolicator:latest'
    volumes:
      - 'sentry-symbolicator:/data'
    command: run
  symbolicator-cleanup:
    image: symbolicator-cleanup-onpremise-local
    build:
      context: ./cron
      args:
        BASE_IMAGE: 'getsentry/symbolicator:latest'
        http_proxy: ****************
        https_proxy: ****************
        ftp_proxy: ****************
    command: '"55 23 * * * gosu symbolicator symbolicator cleanup"'
    volumes:
      - 'sentry-symbolicator:/data'
  web:
    << : *sentry_defaults
    ports:
      - '9000:9000/tcp'
  cron:
    << : *sentry_defaults
    command: run cron
  worker:
    << : *sentry_defaults
    command: run worker
  post-process-forwarder:
    << : *sentry_defaults
    # Increase `--commit-batch-size 1` below to deal with high-load environments.
    command: run post-process-forwarder --commit-batch-size 1
  sentry-cleanup:
    << : *sentry_defaults
    image: sentry-cleanup-onpremise-local
    build:
      context: ./cron
      args:
        BASE_IMAGE: 'sentry-onpremise-local'
        http_proxy: ****************
        https_proxy: ****************
        ftp_proxy: ****************
    command: '"0 0 * * * gosu sentry sentry cleanup --days $SENTRY_EVENT_RETENTION_DAYS"'
volumes:
  onpremise_sentry-data:
    #external: true
  onpremise_sentry-postgres:
    #external: true
  sentry-redis:
    external: true
  sentry-zookeeper:
    external: true
  sentry-kafka:
    external: true
  sentry-clickhouse:
    external: true
  sentry-symbolicator:
    external: true
  sentry-secrets:
  sentry-smtp:
  sentry-zookeeper-log:
  sentry-kafka-log:
  sentry-smtp-log:
```

Can you help me ? 

Regards
