### ISSUE TITLE
network mapping to host for docker-compose build

### ISSUE THREAD

**Issue by neonerd0** [getsentry/onpremise#416]
I am trying to run this docker within a windows hyper-v.
Running `install.sh` would give errors with any `apt-get` related commands:

> deb.debian.org cannot be resolved

I can fix this by manually adding: `network: host` into the docker-compose.yml
```
x-sentry-defaults: &sentry_defaults
  << : *restart_policy
  build:
    network: host 
```

However I still have issues with `x-snuba-defaults: &snuba_defaults` as there is no build context.

Is there a way to configure the docker-compose to use the docker network host by default?
