### ISSUE TITLE
cannot pull images us.gcr.io/sentryio/relay:latest

### ISSUE THREAD

**Issue by cench** [getsentry/onpremise#445]
```
  relay:
    image: "us.gcr.io/sentryio/relay:latest"
    command: 'run --config /etc/relay'
    volumes:
      - type: bind
        source: ./relay
        target: /etc/relay
    depends_on:
      - kafka
      - redis
```

```
Error response from daemon: Get https://us.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
