### ISSUE TITLE
BASE_IMAGE are not updated

### ISSUE THREAD

**Issue by marbon87** [getsentry/onpremise#474]
I had a few errors after updating to latest-version from getsentry/onpremise with the install.sh-script.
The problem was that all docker-images used as BASE_IMAGE like this:
```
  symbolicator-cleanup:
    << : *restart_policy
    image: 'symbolicator-cleanup-onpremise-local'
    build:
      context: ./cron
      args:
        BASE_IMAGE: 'getsentry/symbolicator:latest'
```
were not updated / pulled. 

Does `docker-compose pull ` only updates images that are definied as images, like this?

```
  symbolicator:
    << : *restart_policy
    image: 'getsentry/symbolicator:latest'
    volumes:
      - 'sentry-symbolicator:/data'
    command: run
```
