### ISSUE TITLE
Expose nginx on external Docker network

### ISSUE THREAD

**Issue by schrodingersket** [getsentry/onpremise#482]
In order to allow Docker containers running on the same host as this deployment to utilize Sentry, I think it'd be advantageous to add the current `nginx` container to a named external network with an alias specific to Sentry (since a service name of `nginx` is fairly common in many Docker Compose projects).

This would be something along the lines of:

```
nginx:
    ...
    networks:
        default:
        sentry-public:
            aliases:
                - sentry.local

...
networks:
    sentry-public:
        external: true
```

This external network would be created in `install.sh`.

As before, happy to open a PR for this if this functionality is deemed worth having (:

Thanks in advance!

**Comment by BYK** [comment]
I think this is not a very common case and can easily be achieved by using a `docker-compose.overrides.yml` file. What do you think?

**Comment by schrodingersket** [comment]
Fine by me; mostly just wanted to see if the idea had any interest, since it fit my use-case quite well. (: Will go ahead and close this out.

**Comment by Iliyass** [comment]
I had to reverse proxy sentry using Traefik, thanks to @schrodingersket for `default` keyword and @BYK  for `docker-compose.overrides.yml` solution.

here is my working `docker-compose.overrides.yml` maybe someone would benefit from this.
```
version: '3.4'
networks:
  your_external_network:
    external: true
services:
  nginx:
    networks: 
      default:
      your_external_network:
    labels:
      traefik.enable: true
      traefik.http.routers.sentry.rule: "Host(`Your.sentry.domain`)"
```
