### ISSUE TITLE
Not all crashes are received by Server from native app

### ISSUE THREAD

**Issue by clabordrieVirtuos** [getsentry/onpremise#542]
Hello,

We are testing sentry, we updated to the latest version recently, we see many interesting improvements, in crash collection. But we observed that not all the crash are received.
on the client side we are on sentry-native with a classic C++ app, for onpremise we use commit : c2120aafc94e34ee33420d0afb7f3c1641fbe514
**When we switched to sentry cloud, all the crashes are received**. Is anyone experiencing this ?
Do you have an idea,where I can check some log to get more info.
Thank you very much

**Comment by BYK** [comment]
This is very likely to be related to Relay. Can you share the logs from there? Also make sure you have the latest version of Relay?

//cc @jan-auer

**Comment by jan-auer** [comment]
@clabordrieVirtuos On which platform are you testing the Native SDK and which `sentry-native` backend are you using? We're currently looking into a potential issue that might case large minidumps to get dropped. 

We also enforce maximum size limits for requests and elements of each request. You can observe this with a 413 response status code. These are configurable in your [Relay configuration](https://github.com/getsentry/onpremise/blob/master/relay/config.yml). Official documentation on this will be following soon, but here's a quick outlook on how you could tune this:

```yaml
limits:
  # The maximum payload size for events.
  max_event_size: 1MB,
  # The maximum size for each attachment.
  max_attachment_size: 50MB,
  # The maximum combined size for all attachments in an envelope or request.
  max_attachments_size: 50MB,
  # The maximum payload size for an entire request. Individual limits still apply.
  max_envelope_size: 50MB,
```
