### ISSUE TITLE
[WARNING] sentry.utils.g eo: settings.GEOIP_PATH_MMDB not configured.

### ISSUE THREAD

**Issue by mzch** [getsentry/onpremise#544]
I set `GEOIP_PATH_MMD` in docker-compose.yml, but the following warning is printed:
```
[WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
```
What's wrong?

- docker-compose.yml
```yaml
x-sentry-defaults: &sentry_defaults
  (snip)
  environment:
    SENTRY_CONF: '/etc/sentry'
    SNUBA: 'http://snuba-api:1218'
    GEOIP_PATH_MMD: '/geoip/GeoLite2-City.mmdb'
    SENTRY_REDIS_HOST: 'redis'
  volumes:
    - 'sentry-data:/data'
    - './sentry:/etc/sentry'
    - './geoip:/geoip'
```
