### ISSUE TITLE
Message production error: MessageTimedOut (Local: Message timed out)

### ISSUE THREAD

**Issue by mrvarmazyar** [getsentry/onpremise#687]
I'm receiving this error on sentry docker-compose:

``` 
relay_1                        | 2020-09-29T09:51:36Z [relay_server::utils::kafka] ERROR: failed to produce message to Kafka (delivery callback): Message production error: MessageTimedOut (Local: Message timed out)
```

The Relay config:

```
relay:
  upstream: "http://web:9000/"
  host: 0.0.0.0
  port: 3000
logging:
  level: WARN
processing:
  enabled: true
  kafka_config:
    - {name: "bootstrap.servers", value: "kafka:9092"}
    - {name: "message.max.bytes", value: 50000000} #50MB or bust
  redis: redis://redis:6379
```

It has network access to kafka, but I have no idea how can I fix it?

thanks
