### ISSUE TITLE
Cannot upload avatars, source maps using s3 filestore

### ISSUE THREAD

**Issue by TaylorBriggs** [getsentry/onpremise#719]
## Version Information

Version: 20.10.1

## Description

Uploading an avatar appears to work but upon page refresh the image is not there and the network tab shows a 500 error.

## Steps to Reproduce

1. Navigate to account settings
2. Click "Change photo" under avatar settings
3. Choose a new image and click "Save Avatar"
4. Reload the page
5. See the image will not load

## Logs

[sentry_install_log-2020-10-22_19-18-36.txt](https://github.com/getsentry/onpremise/files/5425326/sentry_install_log-2020-10-22_19-18-36.txt)
[docker_compose_log-2020-10-22.txt](https://github.com/getsentry/onpremise/files/5425328/docker_compose_log-2020-10-22.txt)

**Comment by BYK** [comment]
Seems like a configuration issue to me:

>botocore.exceptions.ClientError: An error occurred (InvalidRequest) when calling the GetObject operation: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

Can you share your `config.yml`, specifically the s3 filestore configuration part?

**Comment by TaylorBriggs** [comment]
I had run into that issue early on and thought it was fixed by my config. Here it is:

```
################
# File storage #
################

# Uploaded media uses these `filestore` settings. The available
# backends are either `filesystem` or `s3`.

# filestore.backend: 'filesystem'
# filestore.options:
#   location: '/data/files'

filestore.backend: 's3'
filestore.options:
  access_key: 'AKxxx'
  secret_key: 'xxx'
  bucket_name: 'sentry-filestore'
  signature_version: 's3v4'
dsym.cache-path: '/data/dsym-cache'
releasefile.cache-path: '/data/releasefile-cache'
```

The thing that caught my eye is nginx warning about temporary files:
> [warn] 6#6: *116 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000001, client: 172.31.45.131, server: , request: "PUT /api/0/users/me/avatar/ HTTP/1.1", host: "sentry.allvision.io", referrer: "https://sentry.allvision.io/settings/account/details/"

This is followed by the 500 error when trying to get the avatar:
> "GET /avatar/f9d4370f13d5463b943132f8e69ec175/ HTTP/1.1" 500 6429 "https://sentry.allvision.io/settings/account/details/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0" "24.148.95.206"

I am running sentry v20.10.1 on EC2 with amazon linux 2; the instance has AWS CLI v1.18.147. I have confirmed that the instance profile has the correct permissions for the bucket on S3 and I am able to use the `aws` command to list buckets, copy objects, etc., from the instance to the bucket in question.
