### ISSUE TITLE
Feature Request: Explicitly define a internal network in docker-compose.

### ISSUE THREAD

**Issue by laundmo** [getsentry/onpremise#770]
## Summary

This is a request to explicitly define docker networks in the docker-compose.

## Motivation

For the purposes of adding sentry onpremise to existing networks, some containers might need to be added to a external network. This will prevent that container from accessing the default network created by docker-compose. To prevent this from happening, all containers need to be explicitly added to a network that they share with all other containers they need access to.

This is important for cases where users may want to reverse-proxy sentry themselves, especially using something like traefik.

**Comment by laundmo** [comment]
@chadwhitacre the bot seems to think this issue isn't accepted.

**Comment by chadwhitacre** [comment]
Sorry @laundmo, bot went haywire due to error on my part. 😖 Should be back on track now ...

**Comment by darklow** [comment]
I wish local network was defined explicitly and available out of the box.
Current quick workaround/hack is adding local network to restart policy block:

```yml
x-restart-policy: &restart_policy
  restart: unless-stopped
  networks:
    - local
 ```

And defining external and local networks in the end of the file:
```yml
...

networks:
  local:
  nginx-proxy:
    external: true
```

Now for nginx service you can add both network and all the rest services will still communicate over `local` network:
```yml
...
  nginx:
    <<: *restart_policy
...
    networks:
      - nginx-proxy
      - local
```
