### ISSUE TITLE
relay unable to connect to web:9000

### ISSUE THREAD

**Issue by durnerj** [getsentry/onpremise#771]
## Version Information

Sentry 20.11.1
Docker version 20.10.0, build 7287ab3
docker-compose version 1.27.4, build 40524192
5.4.0-56-generic Ubuntu 20.04

## Description

Since the upgrade to Docker 20.10 i can run sentry but won't get any Issues in, as the relay Container isn't able to connect to the web container, see the logs appended.

Maybe useful additions:
I have traefik as reverse proxy on the relay and the web container. Both of them are in my proxy network and the default network so they can connect to the other containers. like this:
```
.....
  web:
    << : *sentry_defaults
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sentry.rule=Host(`domain`)"
      - "traefik.http.routers.sentry.middlewares=redirect-to-https"
      - "traefik.http.routers.sentry.service=sentry"
      - "traefik.http.services.sentry.loadbalancer.server.port=9000"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
.....
  relay:
    .....
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sentry-relay.rule=Host(`domain`) && PathPrefix(`/api/store/`, `/api/{id:[1-9]\\d*/}`)"
      - "traefik.http.routers.sentry-relay.middlewares=redirect-to-https"
      - "traefik.http.routers.sentry-relay.service=sentry-relay"
      - "traefik.http.services.sentry-relay.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
.....
```

## Steps to Reproduce

1. update docker to latest version
2. clone this git
3. either set `20.11.1` in `.env` or use `nightly` (no changes, both won't work)
4. run `install.sh`
5. `docker-compose up -d`
6. broken relay container

## Logs

```
2020-12-14T19:37:01Z [relay_server::actors::upstream] INFO: registering with upstream (http://web:9000/)
2020-12-14T19:37:01Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: Failed to connect to host: Failed resolving hostname: no record found for name: web type: AAAA class: IN
  caused by: Failed resolving hostname: no record found for name: web type: AAAA class: IN
  caused by: Failed resolving hostname: no record found for name: web type: AAAA class: IN
2020-12-14T19:37:01Z [relay_server::actors::upstream] DEBUG: scheduling authentication retry in 60 seconds
```

Also things I tried:
Disable traefik -> nope
Install ping package inside relay and ping web -> works
moved all other containers named "web" to a different name -> nope

docker inspect of relay-container isn't giving me a IPv6 address as i have not setup any fancy docker networking things (didn't disable or enable v6/v4 or anything - standard network settings, just larger pools)

this is my `daemon.json`:
```
{
  "features": { "buildkit": true },
  "registry-mirrors": ["https://private.docker.mirror"],
  "default-address-pools":[
    {"base":"172.20.0.0/16","size":24},
    {"base":"172.30.0.0/16","size":24},
    {"base":"172.40.0.0/16","size":24}
  ]
}
```

Hope someone can help, i have no clue what to test anymore.

Let me know when i can add things that maybe help to further track down my problem.

Thanks in advance.
