### ISSUE TITLE
sentry-cleanup does not start

### ISSUE THREAD

**Issue by olexiyb** [getsentry/onpremise#860]
### Version Information

Version: *20.12.0*

### Steps to Reproduce

1. Upgrade to the latest version

### Expected Result

I expect all docker services to start.

### Actual Result

sentry-cleanup-onpremise-local         "/etc/sentry/entrypo…"   4 minutes ago       Restarting (127) 10 seconds ago                                                                                  sentry_onpremise_sentry-cleanup_1

### Logs

```
$ docker logs sentry_onpremise_sentry-cleanup_1 -f
/docker-entrypoint.sh: line 27: exec: 0 0 * * * gosu sentry sentry cleanup --days 90: not found
```

I believe that issue was introduced by
https://github.com/getsentry/onpremise/pull/834#discussion_r575919003

```
  sentry-cleanup:
    <<: *sentry_defaults
    image: sentry-cleanup-onpremise-local
    build:
      context: ./cron
      args:
        BASE_IMAGE: "$SENTRY_IMAGE"
    entrypoint: "/entrypoint.sh" <---- Added line
    command: '"0 0 * * * gosu sentry sentry cleanup --days $SENTRY_EVENT_RETENTION_DAYS"'
```

I was able to start failing service
