### ISSUE TITLE
user:ip behind nginx proxy

### ISSUE THREAD

**Issue by marcelloceschia** [getsentry/onpremise#98]
we are using the 8.22-onbuild and 9-onbuild version behind an nginx proxy server.
When using the csp reporting feature, we only get the docker interface ip as user:ip even if

```
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Client-IP $remote_addr;
proxy_set_header X-Forwared-For $proxy_add_x_forwarded_for;
proxy_set_header X-Request-Id $request_id;
```
defined in nginx configuration

**Comment by Barbery** [comment]
I have the same problem.

**Comment by steffjenl** [comment]
Do you change the sentry.conf.py?

You must set `SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')`

https://docs.sentry.io/server/nginx/

**Comment by Barbery** [comment]
@steffjenl 
Hi, I use http instead of https, and I read the docs, it say:
```
If you’re using SSL, you’ll also need to set the following in sentry.conf.py:

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
```

**Comment by steffjenl** [comment]
@Barbery you use http and not https.

i see an other issue on https://github.com/getsentry/sentry/issues/1254
`SENTRY_USE_X_FORWARDED_FOR = True`

Sentry uses Django as http server. Maybe you have something to the Ansible manual. They also use Django and explain http -> http reverse proxy.
https://docs.ansible.com/ansible-tower/latest/html/administration/proxy-support.html
`REMOTE_HOST_HEADERS = ['HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR', 'REMOTE_HOST']`

**Comment by Barbery** [comment]
@steffjenl 
Hi, I have set the option `SENTRY_USE_X_FORWARDED_FOR = True`, but still not working.

**Comment by steffjenl** [comment]
@Barbery you can't use https?

Maybe you can try to ask in https://github.com/getsentry/sentry/issues/1254

**Comment by Barbery** [comment]
@steffjenl think you very much! finally, it work!

**Comment by steffjenl** [comment]
@Barbery What was the solution? Have you chosen for HTTPS in combination with LetsEncrypt? This is useful information for others who have or are experiencing the same problem.

**Comment by Barbery** [comment]
@steffjenl The key is ngx_http_realip_module, I follow this https://github.com/getsentry/sentry/issues/1254#issuecomment-53113131

**Comment by marcelloceschia** [comment]
I should say that the mentioned configuration above works for all reports generated by the sentry/raven clients. It does not work for `csp reporting`

**Comment by thobruk** [comment]
You have a typo in your config
`proxy_set_header X-Forwared-For $proxy_add_x_forwarded_for;`
Forwarded, Not Forwared. Is that significant ?

**Comment by BYK** [comment]
Closing due to inactivity and not being very relevant to this repo.

**Comment by acidoxee** [comment]
We use Traefik instead of nginx, but we are facing the same problem.

Most apps in our stack are aware of the usage of proxy-protocol and the headers it sets, thus logging/using the correct protocol, host, server and, most importantly, the right IP from the client. 

This is important for logging purposes for instance, for which Koa automatically uses the right proxied info by just setting `app.proxy = true`. Hence our logs do use the right information, not those of the reverse-proxy.

Although, we are failing to make Sentry account for these headers. They are right there, in each Sentry event, but seem totally unused.

We have properly set the env variable `SENTRY_USE_SSL=1`, and the Sentry env status in admin management area reports `SECURE_PROXY_SSL_HEADER:
('HTTP_X_FORWARDED_PROTO', 'https')`. We have also manually added `SENTRY_USE_X_FORWARDED_FOR = True` to our `sentry.conf.py`. None of those things changed anything regarding the usage of proxied headers.

Do we need to do anything else to get this working?

**Comment by BYK** [comment]
@acidoxee have you rebuilt your docker image once you have changed the config file as it wouldn't be picked up otherwise?

**Comment by acidoxee** [comment]
Hi @BYK, we are not building our custom image, we are just using the following config:

```yml
version: '3.6'

x-defaults: &defaults
  image: sentry:9.1.1-onbuild
  networks:
    - sentry
  depends_on:
    - redis
    - postgres
    - memcached
    - smtp
  environment:
    SENTRY_MEMCACHED_HOST: memcached
    SENTRY_REDIS_HOST: redis
    SENTRY_POSTGRES_HOST: postgres
    SENTRY_EMAIL_HOST: smtp
    SENTRY_SECRET_KEY: '<redacted>'
    SENTRY_USE_SSL: 1
  volumes:
    - data:/var/lib/sentry/files
  configs:
    - source: sentry-config-file
      target: /etc/sentry/config.yml
    - source: sentry-config-script
      target: /etc/sentry/sentry.conf.py
  deploy:
    restart_policy:
      condition: on-failure

services:
  smtp:
    image: tianon/exim4
    networks:
      - sentry
    deploy:
      restart_policy:
        condition: on-failure

  memcached:
    image: memcached:1.5-alpine
    networks:
      - sentry
    deploy:
      restart_policy:
        condition: on-failure

  redis:
    image: redis:3.2-alpine
    networks:
      - sentry
    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:9.5
    networks:
      - sentry
    volumes:
      - postgres:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure

  web:
    <<: *defaults
    networks:
      - traefik_net
      - sentry
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.port: '9000'
        traefik.frontend.rule: 'Host:sentry.<redacted>.com'
      restart_policy:
        condition: on-failure

  cron:
    <<: *defaults
    command: run cron

  worker:
    <<: *defaults
    command: run worker

networks:
  traefik_net:
    external: true
  sentry:
    driver: overlay
    name: sentry

configs:
  sentry-config-file:
    external: true
  sentry-config-script:
    external: true

volumes:
  data:
    external: true
    name: sentry-data
  postgres:
    external: true
    name: sentry-postgres

```

Is building a custom image really mandatory to run the python script? We've been wondering about this, since everything works so far for us without building a custom image. We just used that default setup, and I guess the `-onbuild` suffix is useless for our case since the `ONBUILD` directives in the Dockerfile will not be triggered. But still, every other feature in Sentry seems to be working perfectly when using the default image.

Is it possible to use the `/etc/sentry/config.yml` config file instead to account for proxy-protocol headers? Do I need to put any variable elsewhere to make that work?
